#ifndef IDIOMAS_H_
#define IDIOMAS_H_

#include <stdint.h>
    #define _$(A) stringDiccionarioIdioma(idiomaSeleccionado,A)
    #define $$initDiccionario$ extern unsigned char idiomaSeleccionado;extern const char* diccionarios[];
    typedef enum {$_ESPANOL_$ = 0,$_INGLES_$,$_PORTUGUES_$};

    typedef struct
    {
    uint16_t offsetEsp:16;
    uint16_t offsetIng:16;
    uint16_t offsetPor:16;
    }__attribute__((__packed__)) offsetIdiomas;

    extern const char diccionario_Espanol[];
    extern const char diccionario_Ingles[];
    extern const char diccionario_Portugues[];
    extern unsigned char idiomaSeleccionado;
    typedef enum
    {$IDIOMA,$FACT_CORREC,$BRILLO,$CALENDARIO,$SERV_TECNICO,$VOLVER,$CONFIGURACION,$HORA,$MINUTOS,$ANIO,$MES,$DIA,$PASSWORD,$MODO,$CAPMAXIMA,$TOTALCELDA,$SENSIBILIDAD,$DIVISIONES,$VENTANAMOVIL,$KGFILTRO,$LBFILTRO,$CONVERSIONES,$RECORTES,$TIEMPOESTABILIDAD,$UNIDAD,$PUERTOS,$CALIB_CON_PESO,$PROTOCOLO,$PESARCERO,$PESARPATRON,$PATRON,$CANCELAR,$APAGADO,$CONTINUO,$MOBILE,$VNC,$CER,$IMPRESORA_ERROR,$IMPRIMIENDO,$TOTAL,$INFO,$COPIANDO_PEN,$PEN_ERROR,$ADC_ERROR,$LOTE,$BORRAR_MEMORIA,$BORRADO_MEMORIA,$BUSCANDO,$FECHA_DESDE,$FECHA_HASTA,$VER_DATOS,$FECHA,$CABECERA_IMPRESORA,$PREG_BORRAR,$EDITAR_INGREDIENTE,$RECETA,$CARGAS,$EMPEZAR,$CANTIDAD,$CABEZAS,$POR_RECETA,$POR_INGREDIENTE,$POR_LOTE,$POR_FECHA,$TODAS_CARGAS,$TODAS_DESCARGAS,$MAS_MEZCLA,$GUARDAR,$CELDA,$REMOTO,$PASOS_AUTO,$AVISO_ANTICIP,$NINGUNA,$SELECCIONAR_REMOTO,$RECETAS_DE_CARGA,$GUIA_DE_DESCARGA,$MODO_AUTONOMO,$ARMADO,$BASE_KG,$BASE_LB,$BASE_CABEZAS,$NOMBRE,$PREG_BORRAR_1,$PREG_BORRAR_2,$PREG_BORRAR_GUIA,$PREG_BORRAR_RECETA,$PREG_BORRAR_MIXER,$PREG_BORRAR_MEMORIA,$ID_NO_VALIDO,$GUIA_ID,$BASE_1000_KG,$BASE_1000_LB,$BASE_100_CABEZAS,$DESCARGAS,$BACHADA,$PORCION,$AUTONOMO,$ERROR,$FALTAN_DATOS,$RECETA_ID,$AUTONOMO_ID,$TIEMPO_MEZCLA,$CANTIDAD_ABREVIADO,$MEZCLANDO,$INGREDIENTE,$INGRESE_CANTIDAD,$PARCIAL,$MEMORIA_LLENA,$RESTAN,$REGISTROS,$DESCARGAR,$INGRESE_DATOS,$DEBE_PREPARAR,$TIPO,$BUSCAR,$ACTUALIZAR_INGREDIENTES,$ACTUALIZAR_RECETAS,$ACTUALIZAR_GUIAS,$ACTUALIZAR_AUTONOMOS,$GENERAR_XML,$GENERAR_CSV,$ESTABLE_ABREVIADO,$ALERTA,$EN_MEMORIA,$SELECCIONAR_AUTONOMO,$TIPOS_INCOMPATIBLES,$MODO_DE_CARGA,$MANUAL,$RECETAS,$INGREDIENTE_ID,$CARGA_ID,$DESCARGA_ID,$LEYENDO_DATOS,$MODO_DE_DESCARGA,$ELEGIR_GUIA,$ELEGIR_RECETA,$SIGUIENTE,$REGISTRO_ABREVIADO,$SI,$UNIDADKG,$UNIDADLB,$PAUSA,$TARA,$RESET,$ADVERTENCIA,$ASISTENTE_REMOTO,$ACTIVADO,$PENDRIVE_DESACTIVADO,$PREG_APAGAR_1,$PREG_APAGAR_2,$PREG_APAGAR_3,$PREG_CANCEL_1,$PREG_CANCEL_2,$PREG_CANCEL_3,$OPERARIO,$WRONG_PASS,$TRABAJO,$TRABAJOS,$SELECCIONAR,$SIN_ESPACIO,$POR_CABEZA,$TAL_CUAL,$UNA_RACION,$NUEVO,$EDITAR,$BORRAR,$CANT,$CAB,$TIPO_CALCULO,$MEZCLA,$AVISO,$AVISO_ANTICIPADO,$SEL_RECETA,$PU_MEM_LLENA_1,$PU_MEM_LLENA_2,$PU_MEM_LLENA_3,$INGRESE_NOMBRE,$RECETA_INCOMPATIBLE,$REVISE_TRABAJO,$CONTINUAR,$FINALIZAR,$INTENTE_OTRO,$NOMBRE_EN_USO,$MEZ,$AA,$OBJ,$PES,$LOTE_YA_AGREGADO,$POR_TRABAJO,$TODOS_LOS_REGISTROS,$INVALID_PASS,$CONECTADO,$SIN_CONEXION,$PU_MEM_LLENA_4,$TRABAJO_YA_INICIADO,$REINICIAR,$DESCONTAR_CARGA,$QUIERE_DESCONTAR,$LA_CARGA_EXISTENTE,$OPERARIO_NO_ENCONTRADO,$SUPRIMIR_PICOS,$PROTHIFREQ,$ACERQUE_LA_CARAVANA,$AL_LECTOR,$CARAVANA_DETECTADA,$DETECTAR_CORRAL,$PRIORIDAD_DE_VIAJE,$LLENAR_MIXER,$COMPLETAR_CORRAL,COUNT_DICCIONARIO};
    extern const offsetIdiomas diccionario_idiomas[COUNT_DICCIONARIO];
    char* stringDiccionarioIdioma(uint8_t idioma, uint16_t offset);
    #endif /* IDIOMAS_H_ */