#ifndef IDIOMAS_H_
#define IDIOMAS_H_ 
#include <stdint.h>

#define _$(A) stringDiccionarioIdioma(idiomaSeleccionado,A) 
#define $$initDiccionario$ 
extern unsigned char idiomaSeleccionado;
extern const char* diccionarios[]; 
typedef enum {$_ESPANOL_$ = 0,$_INGLES_$,$_PORTUGUES_$}; 
typedef struct { uint16_t offsetEsp :16; uint16_t offsetIng :16; uint16_t offsetPor :16; }__attribute__((__packed__)) offsetIdiomas;
extern const char diccionario_Espanol[]; 
extern const char diccionario_Ingles[]; 
extern const char diccionario_Portugues[]; 
extern unsigned char idiomaSeleccionado; 
typedef enum {$IDIOMA,$FACT_CORREC,$BRILLO,$CALENDARIO,$SERV_TECNICO,$VOLVER,$CONFIGURACION,$HORA,$MINUTOS,$ANIO,$MES,$DIA,$PASSWORD,$MODO,$CAPMAXIMA,$TOTALCELDA,$SENSIBILIDAD,$DIVISIONES,$VENTANAMOVIL,$KGFILTRO,$LBFILTRO,$CONVERSIONES,$RECORTES,$TIEMPOESTABILIDAD,$UNIDAD,$PUERTOS,$CALIB_CON_PESO,$PROTOCOLO,$PESARCERO,$PESARPATRON,$PATRON,$CANCELAR,$APAGADO,$CONTINUO,$MOBILE,$VNC,$CER,$IMPRESORA_ERROR,$IMPRIMIENDO,$TOTAL,$INFO,$COPIANDO_PEN,$PEN_ERROR,$ADC_ERROR,$LOTE,$BORRAR_MEMORIA,$BORRADO_MEMORIA,$BUSCANDO,$FECHA_DESDE,$FECHA_HASTA,$VER_DATOS,$FECHA,$CABECERA_IMPRESORA,$PREG_BORRAR,$EDITAR_INGREDIENTE,$RECETA,$CARGAS,$GUIA,$EMPEZAR,$CANTIDAD,$CABEZAS,$POR_RECETA,$POR_GUIA,$POR_INGREDIENTE,$POR_LOTE,$POR_FECHA,$TODAS_CARGAS,$TODAS_DESCARGAS,$MAS_MEZCLA,$GUARDAR,$CELDA,$REMOTO,$PASOS_AUTO,$AVISO_ANTICIP,$NINGUNA,$SELECCIONAR_REMOTO,$RECETAS_DE_CARGA,$GUIA_DE_DESCARGA,$MODO_AUTONOMO,$ARMADO,$BASE_Kg,$BASE_Lb,$BASE_CABEZAS,$NOMBRE,$PREG_BORRAR_1,$PREG_BORRAR_2,$PREG_BORRAR_GUIA,$PREG_BORRAR_RECETA,$PREG_BORRAR_MIXER,$PREG_BORRAR_MEMORIA,$ID_NO_VALIDO,$GUIA_ID,$BASE_1000_Kg,$BASE_1000_Lb,$BASE_100_CABEZAS,$DESCARGAS,$BACHADA,$PORCION,$AUTONOMO,$ERROR,$FALTAN_DATOS,$RECETA_ID,$AUTONOMO_ID,$TIEMPO_MEZCLA,$CANTIDAD_ABREVIADO,$MEZCLANDO,$INGREDIENTE,$INGRESE_CANTIDAD,$PARCIAL,$MEMORIA_LLENA,$RESTAN,$REGISTROS,$DESCARGAR,$INGRESE_DATOS,$DEBE_PREPARAR,$TIPO,$BUSCAR,$ACTUALIZAR_INGREDIENTES,$ACTUALIZAR_RECETAS,$ACTUALIZAR_GUIAS,$ACTUALIZAR_AUTONOMOS,$GENERAR_XML,$GENERAR_CSV,$ESTABLE_ABREVIADO,$ALERTA,$EN_MEMORIA,$SELECCIONAR_AUTONOMO,$TIPOS_INCOMPATIBLES,$MODO_DE_CARGA,$MANUAL,$RECETAS,$INGREDIENTE_ID,$CARGA_ID,$DESCARGA_ID,$LEYENDO_DATOS,$MODO_DE_DESCARGA,$ELEGIR_GUIA,$ELEGIR_RECETA,$SIGUIENTE,$REGISTRO_ABREVIADO,$SI,$UnidadKg,$UnidadLb,$PAUSA,$TARA,$RESET,$ADVERTENCIA,$ASISTENTE_REMOTO,$ACTIVADO,$PENDRIVE_DESACTIVADO,$PESADA,$GUARDADA,$PB,COUNT_DICCIONARIO}; 
extern const offsetIdiomas diccionario_idiomas[COUNT_DICCIONARIO]; 
char* stringDiccionarioIdioma(uint8_t idioma, uint16_t offset);

#endif /* IDIOMAS_H_ */